### PR TITLE
Add meta for header

### PR DESCRIPTION
**Pull request by ChangJoo-Park**

### CODE REVIEW

**Comment by bernhardreiter** [comment]
Hi, briefly reading over the change, can you describe what it does?

**Comment by ChangJoo-Park** [comment]
@bernhardreiter Sorry I forgot to add description.

It can be using metadata in router.js https://github.com/misterGF/CoPilot/blob/master/src/routes.js#L28

 to

**Comment by bernhardreiter** [comment]
@ChangJoo-Park , ah now I see vue-router switched from "custom fields" (v1.0) to "meta field" (v2). And `./src/components/Dash.vue:          <small>{{ $route.meta.description }}</small>` already uses it. So good addition.

**Comment by misterGF** [comment]
Thanks guys. Will be merging this soon.

**Comment by ChangJoo-Park** [comment]
Thanks :)

**Pull request merged**
