### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by euvl**
Started using sass (#19), added config file with flags to turn on/off fixedLayout, some refactoring. Also replaced VueResource with Axios [(as Vue.js do not favour VueResource anymore)](https://medium.com/the-vue-point/retiring-vue-resource-871a82880af4#.9f1bxtn4q)

### CODE REVIEW

**Comment by koss-shtukert** [comment]
**Great Job!**

**Comment by euvl** [comment]
Some updates might be arguable though, e.g. i've removed private google analytics token (that might have been there for a reason) and replaced VueResource, which is a bit obsolete. Will be happy to discuss any questions with maintainers.

**Comment by misterGF** [comment]
Great PR! Thank you. Will give it a closer look this week.

**Comment by euvl** [comment]
Perfect, thanks @misterGF! 😄

**Comment by shellscape** [comment]
👍 from me

**Comment by misterGF** [comment]
Updated deployed to demo site!

**Pull request merged**
