### PR TITLE
upgrade to vue 2, veux 2 and vue-router 2

### PR DESCRIPTION
**Pull request by timaschew**

### CODE REVIEW

**Comment by ramstein74** [comment]
waiting for it :+1:

**Comment by msatkevich** [comment]
Nice job on update to vue 2!  One thing I noticed is if you click repeatedly on the hamburger while on the dashboard, the content will stretch and stretch some more.

**Comment by misterGF** [comment]
nice find. It's been fixed in the latest commit.

**Comment by bernhardreiter** [comment]
Opening https://copilot.mistergf.io/ in Firefox 45.4.0 the current ESR release from 2016-09-26 routing does not work, the path is actually requested from the server. So when pressing on "Tables" it gets a "Page not found".  Is this a known problem with vue-router 2? (BTW. Where should questions, problem reports and request for copilot logged?)

**Pull request merged**
