### PR TITLE
Upgrade to Vue 2.2.2

### PR DESCRIPTION
**Pull request by oriregev**
Update project using a Vue CLI v2.8.1 webpack project as reference

Important Note: after this upgrade Node v6 is required.

Scaffolded a simple webpack project with Vuew CLI (vue init webpack
<my project>) and updated CoPilot's config files, based on the generated
project.

Many packages were upgraded.
A few notable upgrades are:
vue 2.0.3 -> 2.2.2
vue-router 2.0.1 -> 2.2.0
webpack 1.13.2 -> 2.2.1

### CODE REVIEW

**Comment by mogita** [comment]
Tested on my on-going project by manually copying the changes, all seems well after `yarn upgrade`.

**Comment by misterGF** [comment]
@oriregev Thanks for this. Sorry for the delay. It's a big update so it's taking a little while to approve.
There was a recent commit that conflicts with your changes. Should be an easy fix from what I can see.

033a5a09c48f548acc4e5d27c35906bc758204df

There was an additional cp cmd added in there.

@bernhardreiter If you have some time can you look at this PR and give your blessing as well.
Thanks!

**Comment by bernhardreiter** [comment]
@oriregev thanks for proposing this update. In general I think it is a good idea to do such an update and stay current with official vuejs.

@misterGF I cannot say if and when I may have time to look into this PR, so you may need to move ahead without my input.

**Comment by oriregev** [comment]
@misterGF Great! Thanks 👍

**Pull request merged**
